### ISSUE TITLE
Basic user is unable to deploy TrustyAI-service in the Cluster

### ISSUE THREAD

**Issue by nehachopra27** [trustyai-explainability/trustyai-service-operator#146]
Basic user is unable to deploy trustyai-service in the cluster.  getting error:
<img width="1286" alt="Screenshot 2023-11-10 at 16 49 18" src="https://github.com/trustyai-explainability/trustyai-service-operator/assets/11557840/e488cd61-800f-4246-aac7-9d40c6487357">

```
An error occurred
trustyaiservices.trustyai.opendatahub.io.trustyai.opendatahub.io is forbidden: User "ldap-user11" cannot create resource "trustyaiservices" in API group "trustyai.opendatahub.io.trustyai.opendatahub.io" in the namespace "namespace"
```

**Comment by lugi0** [comment]
Tested with RC2 and a "basic" user is able to deploy the trusty ai service
![image](https://github.com/trustyai-explainability/trustyai-service-operator/assets/82518733/e7184a29-7746-45f1-8f1e-a919c2bb4e09)
