### ISSUE TITLE
[Bug] Deploying Model in a DataScience Project with Trusty service installed, Model doesn't get registered.

### ISSUE THREAD

**Issue by nehachopra27** [trustyai-explainability/trustyai-service-operator#158]
**Describe the bug**
TrustyAI service is unable to register a model in the Data Science project where model is deployed after the service

**Steps To Reproduce**
1. Create a new data science project
2. Deploy trustyai -crd
3. Create a model server and deploy the model

**Expected behavior**
The model doesn't get registered with the service

Version #: 
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): ODH 2.4.0

**Comment by ruivieira** [comment]
Thanks, @nehachopra27.

Can I ask additional information, if available?

- ODH operator version (I'm assuming 2.4.0)
- `DataScienceCluster` used
- Any TrustyAI and/or ODH operator logs?
