### ISSUE TITLE
Move `lm-eval-aas-flask` image to TrustyAI

### ISSUE THREAD

**Issue by ruivieira** [trustyai-explainability/trustyai-service-operator#274]
@yhwang As part of including the necessary LMES images in the TrustyAI build process, should we add the `lm-eval-aas-flask`?
Thanks!

**Comment by yhwang** [comment]
Yes, that is the job's image. Currently, it still contains the Flask app for the old REST APIs. I will strip it down to only the lm-eval + unitxt

**Comment by yhwang** [comment]
Since the PR has been merged, close this issue. Feel free to reopen it if we need extra work.
