### ISSUE TITLE
LM-Eval jobs can't connect to the gRPC server if deployed in a namespace other than the operator's

### ISSUE THREAD

**Issue by ruivieira** [trustyai-explainability/trustyai-service-operator#307]
When deploying an LMEvalJob to the same namespace as the TrustyAI operator it works as expected.

When deploying an LMEvalJob to a different namespace to the TrustyAI operator, the job's pod cannot connect to the gRPC service with a timeout.

Linked to [RHOAIENG-13845](https://issues.redhat.com/browse/RHOAIENG-13845).

**Comment by yhwang** [comment]
#314 should fix this issue. Is there anything we need to address for this issue?

**Comment by ruivieira** [comment]
Thanks @yhwang, deploying on other namespace is working fine now.
