### ISSUE TITLE
Add PVC as storage option for LM-Eval results

### ISSUE THREAD

**Issue by ruivieira** [trustyai-explainability/trustyai-service-operator#325]
For large, full-results (not just summaries) storing the evaluation results in the CR's status is not practical.
An option should be available to persist full evaluation results to PVC.

**Comment by yhwang** [comment]
Here is my thought on this feature, suggestions/comments are welcome
- provide an option to save the outputs, including stdout, stderr, results, and sampling log, to external storage
- for external storage, we can support different types of storage, i.e. PVC, COS, etc. Let's add the PVC for now.

For the argument's sake, the new option is named `Outputs` and under it users can specify a full data struct of the `PersistentVolumeClaim`. LM-Eval controller would create the PVC and mount it on the `/opt/app-root/src/output` and all the outputs would store to the PVC.

**Comment by yhwang** [comment]
If we want to make the case of using an existing PVC easier, the `Outputs` data struct could be:
```go
type Outputs struct {
	// Use an existing PVC to store the outputs
	// +optional
	PersistentVolumeClaimName *string `json:"pvcName,omitempty"`
	// Create a PVC and use it to store the outputs
	// +optional
	PersistentVolumeClaim *corev1.PersistentVolumeClaim `json:"pvc,omitempty"`
}
```
When the `pvcName` is specified, the LM-Eval controller will create the corresponding `volumes` and `volumeMOunts` for the job pod and store the outputs into the PVC.

**Comment by ruivieira** [comment]
Hi @yhwang, thanks for the suggestions. I think that's a good idea.
However, I've added a proposal with https://github.com/trustyai-explainability/trustyai-service-operator/pull/347 that's slightly different, wanted to know your opinion.

IMO the two use cases (for the PVC scope, at the moment) are:
- PVC managed by the operator with minimal configuration
- Give user the ability to provide more specific PVC configurations

I think that adding the ability to specify a full PVC spec under the LMEvalJob CR might be avoided with your `pvcName` suggestion. This adds the freedom to create any custom PVC and just pass the name reference to the LMEvalJob.
For the scenario where we need a PVC to created from the LMEvalJob, we can simply use `pvcManaged`. wdyt?

**Comment by yhwang** [comment]
Your implementation looks great to me. Left a minor comment and I think it's good to go!
