### ISSUE TITLE
Review Condition lifecycle

### ISSUE THREAD

**Issue by danielezonca** [trustyai-explainability/trustyai-service-operator#38]
Each condition should be updated every time there is a reconcile loop but `lastTransaction` should keep track of when the last flip (True->False or False->True) happened.
Make sure every condition has this behaviour and consider the usage of `meta` util for that

This is a sample of code for reference
https://github.com/lburgazzoli/bf2-cos-fleetshard-go/blob/b740af12e62a6f7032aa2ded6450042f1eb3561c/pkg/cos/fleetshard/conditions/conditions.go#L92

**Comment by ruivieira** [comment]
This was implemented in https://github.com/trustyai-explainability/trustyai-service-operator/pull/119, specifically in https://github.com/trustyai-explainability/trustyai-service-operator/pull/119/files#diff-4953649bfbf4b9228ee0bc500048fed1f8ad541845dcebed3f97e9e0e1e287b4R101
