### ISSUE TITLE
Update: ensure using trustyai-explainability module 

### ISSUE THREAD

**Issue by zdtsw** [trustyai-explainability/trustyai-service-operator#67]
Some code still refer to private repo, this need to be updated and sync to downstream repo.

example:
https://github.com/trustyai-explainability/trustyai-service-operator/blob/a33cb8b79a648527fa1e355b2ab38164ea517f53/main.go#L37
https://github.com/trustyai-explainability/trustyai-service-operator/blob/a33cb8b79a648527fa1e355b2ab38164ea517f53/main.go#L38
https://github.com/trustyai-explainability/trustyai-service-operator/blob/main/go.mod#L1

might be some other places as well, need a check

**Comment by ruivieira** [comment]
@zdtsw Thanks for the heads up. All the references to the old repo were replaced with #68.
