### ISSUE TITLE
Service status declared Ready before pods are running

### ISSUE THREAD

**Issue by ruivieira** [trustyai-explainability/trustyai-service-operator#76]
- Add a `status.conditions` with type: `ServiceReady` and status: 'True' when service fully deployed
- Prevent `status.ready == 'True'` before pods are ready

**Comment by alexcreasy** [comment]
I've reproduced this in a couple of ways, be aware the pod does spin up within about 15 seconds on an empty cluster, so you have a short window to catch it. 

The easiest way is to have a dedicated console window open on the pods page for that namespace and have two console windows open, one ready to create the CR, the other with the command typed out ready to retrieve the CR. If you create and then fetch the CR straight after, you'll see it shows as ready before the pod is fully spun up in your browser.
