### ISSUE TITLE
Serving runtime not properly configured if deployed after TrustyAI service

### ISSUE THREAD

**Issue by ruivieira** [trustyai-explainability/trustyai-service-operator#89]
When serving runtimes are deployed after the TrustyAI service CR is applied, in some cases it might not be properly configured.

**Comment by alexcreasy** [comment]
I'll just add some information as to how I'm reproducing this from the dashboard perspective:

1. Create a new Data Science Project (i.e. k8s namespace)
2. Go to the settings tab and click `Enable  TrustyAI`
3. Create a `Data Connection` - I'm using the rhods-public S3 bucket
4. Create a `Model Server`
5. Create a `Model` (i.e. an InferenceService in k8s)
6. Curl data at the model.

When it's done in the above order the curl commands error out. If you perform this sequence but move step 2 to last, everything works as expected.
